meta_product_name: "Club Fever"
meta_title: "Club Fever - Complete quinielas online"
meta_description: "A perfect opportunity to bet on football matches set up by your favourite clubs"
meta_image: "cover.png" # should exist in `app/assets/images/`
